### ISSUE TITLE
Criar o link para as seções.

### ISSUE THREAD

**Issue by jose-ewerton** [jose-ewerton/Trilhas_do_Vale#6]

**Comment by Thali-ctrl** [comment]
Tudo ok nessa aqui também professor. 👍
Maaaaas, temos que trabalhar no alinhamento. E quanto está no responsivo o link aparentemente não funciona.

**Comment by jose-ewerton** [comment]
Certo, vou manter a conversa aqui e eliminar a outra Issue que criei
